name: Push to Amazon ECR

on:
  push:
    branches:
      - master
  

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY : clo835
        IMAGE_TAG: ${{ github.sha }}
        CAT : CATSAPP
        DOG : DOGSAPP
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        cd cats
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$CAT .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$CAT
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$CAT"
        cd dogs
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$DOG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$DOG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG/$DOG"


    
